try 

except

finaly

with


Исключения в Python – это события,
 возникающие во время выполнения программы,
 которые могут привести к ошибкам или аномальному завершению программы.

 Они обычно возникают из-за некорректного кода или непредвиденных ситуаций,
 таких как деление на ноль,
 доступ к несуществующему файлу или использование неопределенной переменной.



Программа, написанная на языке Python, останавливается сразу как обнаружит ошибку. Ошибки могут быть (как минимум) двух типов:

Синтаксические ошибки — возникают, когда написанное выражение не соответствует правилам языка (например, написана лишняя скобка);

Исключения — возникают во время выполнения программы (например, при делении на ноль).

Синтаксические ошибки исправить просто (если вы используете IDE, он их подсветит). А вот с исключениями всё немного сложнее — не всегда при написании программы можно сказать возникнет или нет в данном месте исключение. Чтобы приложение продолжило работу при возникновении проблем, такие ошибки нужно перехватывать и обрабатывать с помощью блока 
try/except
.